import os
import shutil
import urllib.request
import ssl
import zipfile
import hashlib

def main():
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    target = "android_new"
    if os.path.exists(target):
        shutil.rmtree(target)

    os.makedirs(f"{target}/gradle/wrapper", exist_ok=True)
    os.makedirs(f"{target}/app/src/main/java/com/radhajap/app", exist_ok=True)
    os.makedirs(f"{target}/app/src/main/res/values", exist_ok=True)
    os.makedirs(f"{target}/app/src/main/res/xml", exist_ok=True)
    os.makedirs(f"{target}/app/src/main/res/layout", exist_ok=True)
    os.makedirs(f"{target}/app/src/main/assets/public", exist_ok=True)
    os.makedirs(f"{target}/capacitor-cordova-android-plugins/src/main/java", exist_ok=True)

    # 1. Download official fresh gradle-wrapper.jar
    wrapper_url = "https://raw.githubusercontent.com/gradle/gradle/v8.10.2/gradle/wrapper/gradle-wrapper.jar"
    print("Downloading clean gradle-wrapper.jar...")
    req = urllib.request.Request(wrapper_url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, context=ctx) as resp:
        jar_bytes = resp.read()

    jar_dest = f"{target}/gradle/wrapper/gradle-wrapper.jar"
    with open(jar_dest, "wb") as f:
        f.write(jar_bytes)

    print(f"Saved gradle-wrapper.jar: {len(jar_bytes)} bytes, SHA256: {hashlib.sha256(jar_bytes).hexdigest()}")

    with zipfile.ZipFile(jar_dest, "r") as z:
        assert z.testzip() is None, "Downloaded jar is corrupt!"
        print("Verified downloaded gradle-wrapper.jar is 100% valid ZIP/JAR!")

    # 2. gradle-wrapper.properties
    with open(f"{target}/gradle/wrapper/gradle-wrapper.properties", "w") as f:
        f.write("""distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.5-all.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
""")

    # 3. gradlew & gradlew.bat
    if os.path.exists("android/gradlew"):
        shutil.copy2("android/gradlew", f"{target}/gradlew")
        shutil.copy2("android/gradlew.bat", f"{target}/gradlew.bat")
    os.chmod(f"{target}/gradlew", 0o755)

    # 4. Root build.gradle
    with open(f"{target}/build.gradle", "w") as f:
        f.write("""buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
""")

    # 5. settings.gradle
    with open(f"{target}/settings.gradle", "w") as f:
        f.write("""include ':app'
include ':capacitor-cordova-android-plugins'
apply from: 'capacitor.settings.gradle'
""")

    with open(f"{target}/capacitor.settings.gradle", "w") as f:
        f.write("// Auto generated by Capacitor\n")

    # 6. variables.gradle & gradle.properties
    with open(f"{target}/variables.gradle", "w") as f:
        f.write("""ext {
    minSdkVersion = 22
    compileSdkVersion = 34
    targetSdkVersion = 34
    androidxActivityVersion = '1.8.0'
    androidxAppCompatVersion = '1.6.1'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.12.0'
    androidxFragmentVersion = '1.6.2'
    coreSplashScreenVersion = '1.0.1'
    androidxWebkitVersion = '1.9.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.5'
    androidxEspressoCoreVersion = '3.5.1'
    cordovaAndroidVersion = '10.1.1'
}
""")

    with open(f"{target}/gradle.properties", "w") as f:
        f.write("org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nandroid.enableJetifier=true\n")

    # 7. app/build.gradle
    with open(f"{target}/app/build.gradle", "w") as f:
        f.write("""apply plugin: 'com.android.application'

android {
    namespace "com.radhajap.app"
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.radhajap.app"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:${rootProject.ext.androidxAppCompatVersion}"
    implementation "androidx.coordinatorlayout:coordinatorlayout:${rootProject.ext.androidxCoordinatorLayoutVersion}"
    implementation "androidx.core:core-splashscreen:${rootProject.ext.coreSplashScreenVersion}"
    implementation "androidx.webkit:webkit:${rootProject.ext.androidxWebkitVersion}"
}
""")

    # 8. MainActivity.java
    with open(f"{target}/app/src/main/java/com/radhajap/app/MainActivity.java", "w") as f:
        f.write("""package com.radhajap.app;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}
""")

    # 9. AndroidManifest.xml
    with open(f"{target}/app/src/main/AndroidManifest.xml", "w") as f:
        f.write("""<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name=".MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
    </application>

</manifest>
""")

    # 10. Copy res
    if os.path.exists("android/app/src/main/res"):
        for item in os.listdir("android/app/src/main/res"):
            s = os.path.join("android/app/src/main/res", item)
            d = os.path.join(f"{target}/app/src/main/res", item)
            if os.path.isdir(s) and not os.path.exists(d):
                shutil.copytree(s, d)

    # 11. Copy dist web assets
    if os.path.exists("dist"):
        for item in os.listdir("dist"):
            s = os.path.join("dist", item)
            d = os.path.join(f"{target}/app/src/main/assets/public", item)
            if os.path.isdir(s):
                shutil.copytree(s, d, dirs_exist_ok=True)
            else:
                shutil.copy2(s, d)

    # 12. capacitor.config.json
    with open(f"{target}/app/src/main/assets/capacitor.config.json", "w") as f:
        f.write('{\n  "appId": "com.radhajap.app",\n  "appName": "Radha Jaap",\n  "webDir": "public"\n}\n')

    # 13. Plugin stub
    with open(f"{target}/capacitor-cordova-android-plugins/build.gradle", "w") as f:
        f.write("apply plugin: 'com.android.library'\nandroid {\n    namespace \"com.getcapacitor.cordova\"\n    compileSdk rootProject.ext.compileSdkVersion\n}\n")

    with open(f"{target}/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml", "w") as f:
        f.write('<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n</manifest>\n')

    print("SUCCESSFULLY BUILT BRAND NEW ANDROID_NEW PROJECT!")

if __name__ == "__main__":
    main()
